
services:
  nodejs-app:
    image: muriloleal/nodejs-app:latest
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: watchtower