
services:
  frontend-compose:
      build: example-frontend/
      ports:
        - 5000:5000
      # environment:
      #   - REACT_APP_BACKEND_URL=http://localhost:8000
  backend-compose:
      build: example-backend/
      ports:
        - 8000:8080
      environment:
        - REDIS_HOST=redis-compose
        #- REQUEST_ORIGIN=http://localhost:5000
  redis-compose:
      image: redis:alpine