api:
  dashboard: true
  insecure: true

entryPoints:
  postgres:
    address: ":5432"
  redis:
    address: ":6379"
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker: {}